### ISSUE TITLE
Video Screensaver

### ISSUE THREAD

**Issue by talex-tnt** [alextinti83/RetroStation#11]
If some game as any video preview, play it?
Video resolution might not be enough for a full screen rendering..
Investigate.

**Comment by hex007** [comment]
This should help. It has already been implemented. Cheers 

https://retropie.org.uk/forum/topic/8734/please-test-random-game-selection-launch-via-video-screensaver

**Comment by talex-tnt** [comment]
I wasn't planning to work on this any time soon..
but if their implementation works smoothly I'll consider to borrow it.
Thanks ;)

**Comment by hex007** [comment]
@talex-tnt would you consider contributing your time towards Retropie-ES development? I see that you are actively developing ES. May I know if this is for personal use or for something else

**Comment by talex-tnt** [comment]
Hey @hex007, I decided to implement myself  the features I needed since I was seeing very little progress on the RetroPie repo - ES side; they have other priorities AFAIU.

I doubt they're going to merge any of my branches or features implemented though,
I had to do several refactors to the original code base to get them working as I wanted.

Moreover I couldn't really test them to be 100% sure I didn't break some other functionality..

I any case I'll try to back merge their changes time to time, here https://github.com/alextinti83/RetroStation/tree/retropie/sync_to_master

**Comment by talex-tnt** [comment]
https://github.com/RetroPie/EmulationStation/pull/153 was merged to retropie.
I merged retropie master into  [retropie/sync_to_master](https://github.com/talex-tnt/RetroStation/tree/retropie/sync_to_master) and the feature looks working fine.
I'll close this after merging retropie/sync_to_master to dev

**Comment by talex-tnt** [comment]
Merged: 9a35746ec2e82acc2e4c0d1237e60eef99fb879d
