### ISSUE TITLE
Background Music

### ISSUE THREAD

**Issue by talex-tnt** [alextinti83/RetroStation#6]
- Play some background music from some folder.
- Take into account the VLC video support
- Can VLC lib play music? Check SDL mixer otherwise.

**Comment by hex007** [comment]
Kindly check out my implementation of music player. It is a python http server with ffmpeg/avconv backend controlled using curl requests

https://github.com/hex007/EmulationStation

commits for server:
https://github.com/hex007/EmulationStation/commit/4e786329a9b24717cdb5a0b12d896f4d6d740b93

commits for interface:
https://github.com/hex007/EmulationStation/commit/30d5ebeb19357cd8b549d10b117397b30d0bde58

**Comment by talex-tnt** [comment]
It looks interesting, 
@hex007 will it fade out music bg when/if a game video preview starts?
I'll take a look at it this weekend, thanks.

**Comment by hex007** [comment]
I recently started working with previews so It doesnt work with previews as yet. It does pause and continue with emulator execution
