### ISSUE TITLE
Loop through menu entries

### ISSUE THREAD

**Issue by talex-tnt** [alextinti83/RetroStation#8]
Investigate if possible without major refactors

**Comment by hex007** [comment]
Looping through Menu entries has a bug: When you are configuring input, there is no way to exit as you never reach the Back button. 

This was thought of and tried by someone. Cant find it again.

**Comment by talex-tnt** [comment]
I did some quick experiment ending up with that same issue I think..
I have some other ideas but they require more work.. not sure when I'll be able to try them.
